---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue
  namespace: sock-shop
spec:
  template:
    spec:
      containers:
      - name: catalogue
        env:
        - name: env
          value: staging
