---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/locked: "true"
    flux.weave.works/locked_user: Richard Scholz <richard.scholz@senacor.com>
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.4
  name: podinfo
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      $setElementOrder/initContainers:
      - name: init
      containers:
      - image: stefanprodan/podinfo:1.4.4
        name: podinfod
      initContainers:
      - image: alpine:3.10
        name: init
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
    flux.weave.works/locked_user: Richard Scholz <richard.scholz@senacor.com>
  name: catalogue
  namespace: sock-shop
