apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: catalogue
  name: catalogue
  namespace: sock-shop
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    application: catalogue
