apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: front-end
  name: front-end
  namespace: sock-shop  
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: front-end
    spec:
      containers:
      - image: weaveworksdemos/front-end:0.3.12
        name: front-end
        ports:
        - containerPort: 8079
        livenessProbe:
          exec:
            command:
            - wget
            - -O-
            - http://localhost:8079
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - wget
            - -O-
            - http://localhost:8079
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 10
        resources: {}
      hostname: front-end
      restartPolicy: Always
