apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- catalogue-db-deployment.yaml
- catalogue-db-service.yaml
- catalogue-deployment.yaml
- catalogue-service.yaml
- front-end-deployment.yaml
- front-end-service.yaml
- sock-shop-namespace.yaml